### PR TITLE
Process data

### PR DESCRIPTION
**Pull request by rgdonohue**
Data seems cool. I unzipped them and using ogrinfo noticed only the one of the Shapefiles was wgs84. All were unprojected but the others were based off of NAD73 datum. 

I used the commands documented here to convert them to geojson wgs4: https://github.com/MarkCruse/assignment-01/blob/process-data/history_10.18.20:50:54.txt

A quick test when you do this is to throw them into http://geojson.io/, which can also get saved as a Gist when logged into GitHub: https://gist.github.com/rgdonohue/8343278a8ad4b3e23e1fb69bedc5cffb

Although I notice my trails.geojson file is 8+MB in size, so would need to deal with that.

### CODE REVIEW

**Comment by MarkCruse** [comment]
This looks great to me.  I am going to go ahead and merge them,

**Comment by rgdonohue** [comment]
@MarkCruse I didn't do the mask, but maybe that actually forms some polygons with the negative space that we want?

**Comment by MarkCruse** [comment]
@rgdonohue  I will check into the mask. I've uploaded a first pass at the map. I want to add streams and didn't find anything on GRSM.  Should I just download them from another location?

**Comment by rgdonohue** [comment]
Yeah, was just thinking this map needs some streams. Yes see if you can find a good source elsewhere?

**Comment by MarkCruse** [comment]
What I really want is a topo background. Like what is shown when the json files are dropped into geojson.io  I've been looking around but I can't tell what tileset(?) they are using

**Pull request merged**
